Bump the rust toolchain version
After running cargo update, the following change was added

updating clap_lex v0.5.0 -> v0.5.1

This made it so that the project failed to build with the following
error

error: package `clap_builder v4.4.0` cannot be built because it
requires rustc 1.70.0 or newer, while the currently active rustc
version is 1.67.1
Either upgrade to rustc 1.70.0 or newer, or use
cargo update -p clap_builder@4.4.0 --precise ver
where `ver` is the latest version of `clap_builder` supporting rustc 1.67.1

So I've bumped the version to the latest stable version